### ISSUE TITLE
Add some kind of UI to Decay Manager to show how long until craft despawn

### ISSUE THREAD

**Issue by severedsolo** [severedsolo/KesslerSyndrome#4]

**Comment by theonegalen** [comment]
Ooh
Would you time this until atmospheric interface, until the time the periapsis drops below say 40 km or something like that?

**Comment by severedsolo** [comment]
@theonegalen Basically yes, it would be time to KSP autodeleting the craft (if it happens at all)

**Comment by severedsolo** [comment]
Decay manager is removed, so issue is no longer relevant
